#!/usr/bin/env python

import unittest
from app.views import app

class AppTestCase(unittest.TestCase):

  def setUp(self):
    app.config['TESTING'] = True
    self.app = app.test_client()

  def test_index(self):
    self.app.get('/')

if __name__ == '__main__':
  unittest.main()